version: '3.8'
services:
  zookeeper_server:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    networks:
      nlp_bridge:
        ipv4_address: 172.20.0.3

  kafka_server:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper_server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.20.0.4:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
    ports:
        - '9092:9092'
    depends_on:
      - zookeeper_server
    networks:
      nlp_bridge:
        ipv4_address: 172.20.0.4

  nlp_engine:
    container_name: nlp_engine
    build: ./NLPEngine
    depends_on:
      - kafka_server
    volumes:
      - ./NLPEngine:/app
    ports:
      - '5001:5001'
    networks:
      nlp_bridge:
        ipv4_address: 172.20.0.5
    command: python app.py -p 5001 -b
    healthcheck:
      test: curl --insecure -f https://nlp_engine:5001/health
      start_period: 10s
      timeout: 2s
      retries: 2

  dialog_engine:
    container_name: dialog_engine
    build: ./DialogEngine
    depends_on:
      nlp_engine:
        condition: service_healthy
    volumes:
      - ./DialogEngine:/app
    ports:
      - '5002:5002'
    networks:
      nlp_bridge:
        ipv4_address: 172.20.0.6
    command: java -jar hmi.jar -i rest -r trip_en -p 5002 -b

networks:
  nlp_bridge:
    driver: bridge
    ipam: 
      config: 
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1